set(CMAKE_EXPORT_COMPILE_COMMANDS ON CACHE BOOL "Enable/Disable output of compile commands during generation.")
mark_as_advanced(CMAKE_EXPORT_COMPILE_COMMANDS)
list(FIND LANGUAGES CXX index)
if(${index} EQUAL -1)
  list(INSERT LANGUAGES 0 CXX)
endif()
list(FIND LANGUAGES C index)
if(${index} EQUAL -1)
  list(INSERT LANGUAGES 0 C)
endif()
set(index)
